version: "3.7"

services:
  web:
    build: .
    command: > 
      sh -c 
        "python manage.py makemigrations phonebook &&
        python manage.py migrate phonebook &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"

    environment:
      - DATABASE_URL=sqlite:////code/db.sqlite3
    depends_on:
      - db

  db:
    image: "drupalci/sqlite-3:dev"
    volumes:
      - ./data:/data

volumes:
  static_volume:
  media_volume:
  sqlite-data:

      